POST http://localhost:3000/auth/v1/user/create
Content-Type: application/json

{
    "email":"fransbell@gmail.com",
    "username":"franistasia",
    "password":"66666666"
}
###

POST http://localhost:3000/auth/v1/user/login
Content-Type: application/json

{
    "username":"franista",
    "password":"66666666"
}

###
POST http://localhost:3000/auth/v1/user/verify
Content-Type: application/json

{
    "tokenId":"7ee98613-05b4-4834-84da-7d44adae8ea2"
}

###
POST http://localhost:3000/auth/v1/user/logout
Content-Type: application/json

{
    "tokenId":"7ee98613-05b4-4834-84da-7d44adae8ea2"
}

###
GET https://blisshub.deta.dev/